spring.application.name=pedido-processor

# Conexão com o Banco de Dados (Mesmo do Módulo A)
spring.datasource.url=jdbc:h2:mem:pedidodb
spring.datasource.username=Gabho
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Conexão com o RabbitMQ do Módulo A
spring.rabbitmq.addresses=amqps://msazqtfd:neim1x3NO9QFNHROB-_kWOE7JzkfCyyp@jackal.rmq.cloudamqp.com/msazqtfd